### ISSUE TITLE
inventory images not showing

### ISSUE THREAD

**Issue by m-boyd** [joshlam/calteach#195]
The images of all items in the Cal Teach Inventory have suddenly stopped displaying. What's going on?

**Comment by CalTeach** [comment]
Do you still have the images? We'd like to transfer them to a new AWS account and have the inventory begin retrieving them from there.

**Comment by joshlam** [comment]
I'm not sure if she still has the images, but I can help get the new AWS account connected to the inventory once that is setup

**Comment by CalTeach** [comment]
Emailing you specifics about getting a new AWS account connected.

**Comment by joshlam** [comment]
https://github.com/joshlam/calteach/commit/0fec57d12b07d90daea33dfe7ce1a3ba64ca9904
