### ISSUE TITLE
Specified "Date In" values for reserved items reset to policy default after check out

### ISSUE THREAD

**Issue by CalTeach** [joshlam/calteach#200]
Admins should be able to adjust the return date of a reservation, click "Check Out", and see the previously specified return date as the return date for the check out.

**Comment by CalTeach** [comment]
I just noticed that any return date specified for a check out is overwritten by the item due date category after trying to check out an item to someone for two weeks only to see that it was recorded for one.

**Comment by joshlam** [comment]
Change for this is up

**Comment by CalTeach** [comment]
Thanks!
